### ISSUE TITLE
识别车牌可以出数据，但是会参数错误，有人遇到吗

### ISSUE THREAD

**Issue by github-mst** [szad670401/HyperLPR#137]
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    image,res = pp.SimpleRecognizePlateByE2E(image)
  File "/home/fuin/.pyenv/versions/3.5.2/lib/python3.5/site-packages/hyperlpr_py3/pipline.py", line 171, in SimpleRecognizePlateByE2E
    image_rgb = fm.findContoursAndDrawBoundingBox(plate)
  File "/home/fuin/.pyenv/versions/3.5.2/lib/python3.5/site-packages/hyperlpr_py3/finemapping.py", line 41, in findContoursAndDrawBoundingBox
    imagex, contours, hierarchy = cv2.findContours(binary_niblack.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by github-mst** [comment]
我自己搞定了。finemapping.py第41行
imagex, contours, hierarchy = cv2.findContours(binary_niblack.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
↓
contours, hierarchy = cv2.findContours(binary_niblack.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

3个变量改成2个就行了

**Comment by panda-lab** [comment]
先不关闭了，留给后面的小伙伴参考吧 O(∩_∩)O~

**Comment by ShaneYS** [comment]
我感觉finemapping用了还不如不用，用之后bounding box的效果更差了
