### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by kkxl490** [szad670401/HyperLPR#176]
运行HyperLPRGUi.py文件时，出现错误
`Traceback (most recent call last):

  File "C:/Users/han/PycharmProjects/hyperlpr/HyperLprGUI.py", line 468, in read_path_and_show_one_image
    self.recognize_and_show_one_image(self.image_filename_list[0], 0)

  File "C:/Users/han/PycharmProjects/hyperlpr/HyperLprGUI.py", line 570, in recognize_and_show_one_image
    image, res_set = SimpleRecognizePlateWithGui(image)

  File "C:/Users/han/PycharmProjects/hyperlpr/HyperLprGUI.py", line 65, in SimpleRecognizePlateWithGui
    image_rgb = pp.fm.findContoursAndDrawBoundingBox(plate)

  File "C:\Users\han\PycharmProjects\hyperlpr\finemapping.py", line 38, in findContoursAndDrawBoundingBox
    cv2.CHAIN_APPROX_SIMPLE)

ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by panda-lab** [comment]
你的opencv 什么版本？

**Comment by kkxl490** [comment]
> 
> 
> 你的opencv 什么版本？

用的Pycharm,里面安装的opencv-python4.1.0.25

**Comment by kkxl490** [comment]
> 
> 
> 你的opencv 什么版本？

运行例程时也出现这个问题
`from hyperlpr import  pipline as  pp

import cv2

image = cv2.imread("./car/1.jpg")

image,res  = pp.SimpleRecognizePlate(image)

print(res)`

结果也是：

`Traceback (most recent call last):

  File "demo1.py", line 4, in <module>
    image,res  = pp.SimpleRecognizePlate(image)

  File "C:\Users\han\Desktop\Jupyter\LPR\hyperlpr\pipline.py", line 199, in SimpleRecognizePlate
    image_rgb = fm.findContoursAndDrawBoundingBox(plate)

  File "C:\Users\han\Desktop\Jupyter\LPR\hyperlpr\finemapping.py", line 41, in findContoursAndDrawBoundingBox
    imagex, contours, hierarchy = cv2.findContours(binary_niblack.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by kkxl490** [comment]
已解决。issue137有类似答案。我把opencv4.1降级为3.4.成功了，可能是版本太新的问题
