### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by truetone2022** [szad670401/HyperLPR#197]
>>> from hyperlpr import *
>>> import cv2
>>> image = cv2.imread("demo.jpg")
>>> print(HyperLPR_PlateRecogntion(image))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/penghuan/anaconda3/envs/HyperLPR/lib/python3.6/site-packages/hyperlpr/__init__.py", line 13, in HyperLPR_PlateRecogntion
    return PR.plateRecognition(Input_BGR,minSize,charSelectionDeskew)
  File "/Users/penghuan/anaconda3/envs/HyperLPR/lib/python3.6/site-packages/hyperlpr/hyperlpr.py", line 189, in plateRecognition
    images = self.detectPlateRough(image,image.shape[0],minSize=minSize)
AttributeError: 'NoneType' object has no attribute 'shape'

Any help is appreciated! Thx!

**Comment by panda-lab** [comment]
it seems failed to read the image
