### ISSUE TITLE
调用RecognizePlateJson会报编码错误

### ISSUE THREAD

**Issue by liugt34** [szad670401/HyperLPR#206]
```
from hyperlpr import pipline as pp
import cv2

image = cv2.imread("car/4.png")
image, res = pp.RecognizePlateJson(image)
print("===================================================")
print(res)

```
WARNING:tensorflow:From D:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:1204: calling reduce_max_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
(678, 1269, 3)
res 川AZ318
校正角度 h  0 v 90
keras_predict [0.08443621 0.95771086]
851c7c3d
e2e: 川AZ318B8
Traceback (most recent call last):
  File "C:/Users/Tom/PycharmProjects/Car/demo.py", line 5, in <module>
    image, res = pp.RecognizePlateJson(image)
  File "D:\ProgramData\Anaconda3\lib\hyperlpr\pipline.py", line 148, in RecognizePlateJson
    print(json.dumps(jsons,ensure_ascii=False,encoding="gb2312"))
  File "D:\ProgramData\Anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'

Process finished with exit code 1

**Comment by dyh** [comment]
修改pipline.py 文件中的2行：

    # print(json.dumps(jsons,ensure_ascii=False,encoding="gb2312"))
    print(json.dumps(jsons, ensure_ascii=False))

    # return json.dumps(jsons,ensure_ascii=False,encoding="gb2312")
    return json.dumps(jsons, ensure_ascii=False)
