### ISSUE TITLE
ubuntu 16.04, opencv 3.4.2

### ISSUE THREAD

**Issue by northeastsquare** [szad670401/HyperLPR#218]
ubuntu 16.04, opencv 3.4.2 遇到如下错误，什么问题呢？

print(HyperLPR_plate_recognition(image))
(1, 3, 533, 400)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/silva/anaconda3/envs/py372/lib/python3.7/site-packages/hyperlpr/__init__.py", line 8, in HyperLPR_plate_recognition
    return PR.plate_recognition(Input_BGR,minSize,charSelectionDeskew)

  File "/home/silva/anaconda3/envs/py372/lib/python3.7/site-packages/hyperlpr/hyperlpr.py", line 305, in plate_recognition

    images = self.detect_ssd(image)

  File "/home/silva/anaconda3/envs/py372/lib/python3.7/site-packages/hyperlpr/hyperlpr.py", line 51, in detect_ssd

    cvOut = self.ssd_detection.forward()

cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:507: error: 

(-215:Assertion failed) input.type() == output.type() in function 'run'

**Comment by panda-lab** [comment]
你试试opencv 3.4.3 ，另外看一下模型加载成功与否，图片路径是否正确。
