### ISSUE TITLE
DNN error

### ISSUE THREAD

**Issue by Mrils** [szad670401/HyperLPR#225]
你好，当我运行print(HyperLPR_plate_recognition(image))这行代码的时候，会报错，请您帮忙看一下。报错信息如下：

OpenCV Error: Assertion failed ((numPriors * _numLocClasses * 4) == inputs[0][1]) in getMemoryShapes, file /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp, line 201
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yh/.local/lib/python2.7/site-packages/hyperlpr/__init__.py", line 8, in HyperLPR_plate_recognition
    return PR.plate_recognition(Input_BGR,minSize,charSelectionDeskew)
  File "/home/yh/.local/lib/python2.7/site-packages/hyperlpr/hyperlpr.py", line 305, in plate_recognition
    images = self.detect_ssd(image)
  File "/home/yh/.local/lib/python2.7/site-packages/hyperlpr/hyperlpr.py", line 51, in detect_ssd
    cvOut = self.ssd_detection.forward()
cv2.error: /io/opencv/modules/dnn/src/layers/detection_output_layer.cpp:201: error: (-215) (numPriors * _numLocClasses * 4) == inputs[0][1] in function getMemoryShapes

环境：ubuntu 18.04  python2.7 opencv 3.4.0 numpy 1.16.6

**Comment by AlanNewImage** [comment]
升级opencv到3.4.3.18
pip install opencv-python==3.4.3.18
