### ISSUE TITLE
webApi.py运行报错 Tensor("activation_19/Softmax:0", shape=(?, 5), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by zhupengfeivip** [szad670401/HyperLPR#254]
运行环境
conda 4.7.12
python 3.6

```
(demo236) PS D:\MyProject\carnum1> conda --version
conda 4.7.12
(demo236) PS D:\MyProject\carnum1> python --version
Python 3.6.10 :: Anaconda, Inc.
```

运行
```
python .\WebAPI.py
Using TensorFlow backend.
2020-05-10 21:29:43.899466: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
WARNING:tensorflow:From D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py:1255: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py:2857: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py:1340: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py:1204: calling reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\Soft\Anaconda3\envs\demo236\lib\site-packages\tensorflow\python\util\tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
 * Serving Flask app "WebAPI" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
127.0.0.1 - - [10/May/2020 21:30:10] "[37mGET /uploader HTTP/1.1[0m" 200 -
127.0.0.1 - - [10/May/2020 21:30:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
(333, 500, 3)
[2020-05-10 21:30:23,260] ERROR in app: Exception on /uploader [POST]
Traceback (most recent call last):
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\WebAPI.py", line 67, in upload_file
    image,res  = pipline.SimpleRecognizePlate(image)
  File "D:\Soft\Anaconda3\envs\demo236\lib\hyperlpr\pipline.py", line 195, in SimpleRecognizePlate
    ptype = td.SimplePredict(plate)
  File "D:\Soft\Anaconda3\envs\demo236\lib\hyperlpr\typeDistinguish.py", line 53, in SimplePredict
    res = np.array(model.predict(np.array([image]))[0])
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\models.py", line 939, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\engine\training.py", line 1745, in predict
    self._make_predict_function()
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\engine\training.py", line 1029, in _make_predict_function
    **kwargs)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py", line 2356, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\keras\backend\tensorflow_backend.py", line 2305, in __init__
    with tf.control_dependencies(self.outputs):
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\tensorflow\python\framework\ops.py", line 4604, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\tensorflow\python\framework\ops.py", line 4310, in control_dependencies
    c = self.as_graph_element(c)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\tensorflow\python\framework\ops.py", line 3323, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "D:\Soft\Anaconda3\envs\demo236\lib\site-packages\tensorflow\python\framework\ops.py", line 3402, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("activation_19/Softmax:0", shape=(?, 5), dtype=float32) is not an element of this graph.
```

参考配置教程
https://www.jianshu.com/p/7ab673abeaae
组件安装脚本及对应版本
python -m pip install hyperlpr -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

pip install keras==2.0.9 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install Theano -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install numpy==1.16.0 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install Scipy -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install opencv-python==3.4.3.18 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install scikit-image -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install pillow -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install tensorflow==1.2.0 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
pip install h5py

pip install flask -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

tensorflow试过1.2，1.5，2.2等版本都未能解决问题。
拜托帮忙看一下，非常感谢，搞了几个晚上了，网上好多方法都试过了，一直没解决。5555555

**Comment by liuyan37** [comment]
The solution is like this website, https://blog.csdn.net/donaldsy/article/details/95097024
Like in your example, you should add 
import tensorflow as tf
graph = tf.get_default_graph()
and then,
with graph.as_default():
    res = np.array(model.predict(np.array([image]))[0])
in the file typeDistinguish.py. And if other files occur the same error, change it in the same way, maybe you need to rectify almost 6 python files.
It works for me.

**Comment by zhupengfeivip** [comment]
> The solution is like this website, https://blog.csdn.net/donaldsy/article/details/95097024
> Like in your example, you should add
> import tensorflow as tf
> graph = tf.get_default_graph()
> and then,
> with graph.as_default():
> res = np.array(model.predict(np.array([image]))[0])
> in the file typeDistinguish.py. And if other files occur the same error, change it in the same way, maybe you need to rectify almost 6 python files.
> It works for me.

你好，我按照您说的方法，试过修改了所有的Python文件，但都没有任何变化？能否把你修改的6个文件发给我呢，或者直接把你能还运行的项目压缩一下发给我？谢谢！！！
邮箱506921467@qq.com

**Comment by zhupengfeivip** [comment]
此问题已在03f5dbf1b92bf278d7bd08df075c121868c918e6版本中解决。请下载最新版本即可。
