### ISSUE TITLE
mac使用失败

### ISSUE THREAD

**Issue by huang443765159** [szad670401/HyperLPR#275]
已经编译成功了，但是我在引用pipline的时候，numpy.AxisError: axis 3 is out of bounds for array of dimension 3报错

**Comment by huang443765159** [comment]
/usr/bin/python3 /Users/huangkai/PycharmProjects/Camera/V3/Test.py
Traceback (most recent call last):
  File "/Users/huangkai/PycharmProjects/Camera/V3/Test.py", line 7, in <module>
    print(HyperLPR_plate_recognition(image))
  File "/Users/huangkai/Library/Python/3.7/lib/python/site-packages/hyperlpr/__init__.py", line 8, in HyperLPR_plate_recognition
    return PR.plate_recognition(Input_BGR,minSize,charSelectionDeskew)
  File "/Users/huangkai/Library/Python/3.7/lib/python/site-packages/hyperlpr/hyperlpr.py", line 305, in plate_recognition
    images = self.detect_ssd(image)
  File "/Users/huangkai/Library/Python/3.7/lib/python/site-packages/hyperlpr/hyperlpr.py", line 39, in detect_ssd
    _im = im.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by huang443765159** [comment]
from hyperlpr import *
# 导入OpenCV库
import cv2
# 读入图片
image = cv2.imread("0.jpeg")
# 识别结果
print(HyperLPR_plate_recognition(image))

**Comment by huang443765159** [comment]
在mac运行此代码错误，
