### ISSUE TITLE
cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:507: error: (-215:Assertion failed) input.type() == output.type() in function 'run'

### ISSUE THREAD

**Issue by MangoLuo** [szad670401/HyperLPR#309]
pip安装后，调用接口报错：
Traceback (most recent call last):
  File "plate_accuracy.py", line 26, in <module>
    for pstr,confidence,rect in HyperLPR_plate_recognition(frame):
  File "/usr/local/python3.6/lib/python3.6/site-packages/hyperlpr/__init__.py", line 8, in HyperLPR_plate_recognition
    return PR.plate_recognition(Input_BGR,minSize,charSelectionDeskew)
  File "/usr/local/python3.6/lib/python3.6/site-packages/hyperlpr/hyperlpr.py", line 305, in plate_recognition
    images = self.detect_ssd(image)
  File "/usr/local/python3.6/lib/python3.6/site-packages/hyperlpr/hyperlpr.py", line 51, in detect_ssd
    cvOut = self.ssd_detection.forward()
cv2.error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:507: error: (-215:Assertion failed) input.type() == output.type() in function 'run'

**Comment by gdjmck** [comment]
I met the same issue and it was fixed by changing the data type of **im_tensor** from not specified to **np.float32**.
The code was in **site-packages/hyperlpr/hyperlpr.py** where you installed this package from pip.
