### ISSUE TITLE
添加openCV module后，运行apk直接报错

### ISSUE THREAD

**Issue by SunPointed** [szad670401/HyperLPR#34]
能否添加一个android导入教程，cmakelists修改过了
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: pr.platerecognization, PID: 22949
                                                                       java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/pr.platerecognization-1/base.apk"],nativeLibraryDirectories=[/data/app/pr.platerecognization-1/lib/arm64, /data/app/pr.platerecognization-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libhyperlpr.so"
                                                                           at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                           at java.lang.System.loadLibrary(System.java:1567)
                                                                           at pr.platerecognization.PlateRecognition.<clinit>(PlateRecognition.java:9)
                                                                           at pr.platerecognization.PlateRecognition.InitPlateRecognizer(Native Method)
                                                                           at pr.platerecognization.MainActivity.initRecognizer(MainActivity.java:139)
                                                                           at pr.platerecognization.MainActivity.onCreate(MainActivity.java:335)
                                                                           at android.app.Activity.performCreate(Activity.java:6912)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
                                                                           at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by szad670401** [comment]
修改一下java warpper中的包名。

**Comment by 0830arthur** [comment]
"PlateRecognition.java" 中的這行代碼出錯 ===> System.loadLibrary("hyperlpr");
找不到 hyperlpr. 請問該如何取得這 Library??
