### ISSUE TITLE
When i import hyperlpr3 as lpr3 something error

### ISSUE THREAD

**Issue by Zomcxj** [szad670401/HyperLPR#393]
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\Software\Anaconda3\envs\DL\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))      

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "car_rec.py", line 4, in <module>
    import hyperlpr3 as lpr3
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\hyperlpr3\__init__.py", line 1, in <module>
    from .hyperlpr3 import LicensePlateCatcher
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\hyperlpr3\hyperlpr3.py", line 9, in <module>
    initialization()
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\hyperlpr3\config\configuration.py", line 62, in initialization
    down_model_zip(target_url, _DEFAULT_FOLDER_, True)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\hyperlpr3\config\configuration.py", line 24, in down_model_zip
    resp = requests.get(url, stream=True)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Software\Anaconda3\envs\DL\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by tunmx** [comment]
From what you're describing, it seems like unstable network issues are preventing you from downloading the necessary resources from a remote server. I'd suggest trying to: 

- Adjust your network and try multiple times;
- Download the resource package and manually install it. Url is http://hyperlpr.tunm.top/raw/20230229.zip , unzip it and place it in the .hyperlpr3 folder in your user's root directory.

**Comment by qianxiaoer** [comment]
哈罗，邮件收到了，我会尽快查看，回复，谢谢！
