### ISSUE TITLE
使用宝塔安装hyperlpr3后引用报错

### ISSUE THREAD

**Issue by GideonLiu** [szad670401/HyperLPR#399]
使用宝塔安装hyperlpr3后，启动项目报错 服务器是centos8.0 python版本3.8.5 宝塔版本7.1.0

以下是输出日志：
[2024-07-18 17:13:38 +0800] [30450] [INFO] Worker exiting (pid: 30450)
[2024-07-18 17:13:38 +0800] [30446] [ERROR] Worker (pid:30450) exited with code 3
[2024-07-18 17:13:38 +0800] [30446] [ERROR] Shutting down: Master
[2024-07-18 17:13:38 +0800] [30446] [ERROR] Reason: Worker failed to boot.
[2024-07-18 17:13:39 +0800] [30471] [INFO] Starting gunicorn 22.0.0
[2024-07-18 17:13:39 +0800] [30471] [INFO] Listening at: http://0.0.0.0:8081 (30471)
[2024-07-18 17:13:39 +0800] [30471] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-07-18 17:13:39 +0800] [30478] [INFO] Booting worker with pid: 30478
[2024-07-18 17:13:39 +0800] [30478] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/hyperlpr/app.py", line 3, in <module>
    import hyperlpr3 as lpr3
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/hyperlpr3/__init__.py", line 1, in <module>
    from .hyperlpr3 import LicensePlateCatcher
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/hyperlpr3/hyperlpr3.py", line 1, in <module>
    from .config.settings import onnx_runtime_config as ort_cfg
  File "/www/wwwroot/hyperlpr/hyperlpr_venv/lib/python3.8/site-packages/hyperlpr3/config/settings.py", line 9, in <module>
    _DEFAULT_FOLDER_ = os.path.join(os.environ['HOME'], ".hyperlpr3")
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
[2024-07-18 17:13:39 +0800] [30478] [INFO] Worker exiting (pid: 30478)
[2024-07-18 17:13:39 +0800] [30471] [ERROR] Worker (pid:30478) exited with code 3
[2024-07-18 17:13:39 +0800] [30471] [ERROR] Shutting down: Master
[2024-07-18 17:13:39 +0800] [30471] [ERROR] Reason: Worker failed to boot.

**Comment by qianxiaoer** [comment]
哈罗，邮件收到了，我会尽快查看，回复，谢谢！
