### ISSUE TITLE
在一个程序中连续两次以上调用识别的函数提示错误

### ISSUE THREAD

**Issue by DayChan** [szad670401/HyperLPR#62]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daychan/Desktop/zqxt_views/calc/views.py", line 40, in add2
    return HttpResponse(test.recong(path))
  File "/home/daychan/Desktop/zqxt_views/calc/test.py", line 14, in recong
    model1 = pr.LPR("model/cascade.xml","model/model12.h5","model/ocr_plate_all_gru.h5")
  File "/home/daychan/Desktop/zqxt_views/calc/HyperLPRLite.py", line 18, in __init__
    self.modelFineMapping.load_weights(model_finemapping)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2656, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 3382, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2373, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1083, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder_4:0", shape=(3, 3, 16, 32), dtype=float32) is not an element of this graph.
```

如果只调用一次则没错

识别的函数是这样写的
``` python
#coding:utf-8
from __future__ import unicode_literals
import HyperLPRLite as pr
import cv2
import numpy as np


from django.shortcuts import render
from django.http import HttpResponse

def recong(path):
	
	grr = cv2.imread(str(path))
	model1 = pr.LPR("model/cascade.xml","model/model12.h5","model/ocr_plate_all_gru.h5")

	for pstr,confidence,rect in model1.SimpleRecognizePlateByE2E(grr):
		if confidence>0.7:
		    
		    print("plate_str",pstr[-6:])
		    print("plate_confidence",confidence)



	cv2.waitKey(0)
	return pstr
```

**Comment by szad670401** [comment]
可以尝试新的更新 通过pip安装

**Comment by DayChan** [comment]
Thank you
